### ISSUE TITLE
feat: portable kitty.conf without hardcoded path

### ISSUE THREAD

**Issue by tummetott** [mikesmithgh/kitty-scrollback.nvim#114]
Hello,

Regrettably, Kitty doesn't natively support the expansion of environment variables within its configuration file. This limitation necessitates specifying hard-coded paths when creating the alias for the KSN kitten. In my case:

```
action_alias kitty-scrollback_nvim kitten /Users/jonas/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
```

This approach leads to a configuration that is neither generic nor portable, which is not ideal. However, I've discovered a workaround that I'd like to share: When using `lazy.nvim`, you can create a symbolic link within the build function:

```lua
build = function()
    local source = vim.fn.stdpath('data') .. '/lazy/kitty-scrollback.nvim'
    local target = vim.env.XDG_CONFIG_HOME .. '/kitty'
    local command = string.format("ln -s '%s' '%s'", source, target)
    os.execute(command)
end,
```

With this setup, the alias in `kitty.conf` can be simplified, since Kitty automatically looks in its configuration directory when specifying relative paths:

```
action_alias kitty-scrollback_nvim kitten kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
```

This modification results in a Kitty configuration that is both portable and more versatile.

**Comment by tummetott** [comment]
> Have you seen any issues with kitty-scrollback.nvim after this change to your config?

Initially, I tried symlinking just the `kitty_scrollback_nvim.py` file, but I encountered Python errors due to this script loading other Python files in the same directory. As a result, I opted to symlink the entire plugin directory, which has been working seamlessly without any issues so far.

>  If you have any other ideas on how the configuration can be improved, feel free to share 👍

I have an additional suggestion to further simplify the configuration process. It would be highly beneficial if configuration entries could accept both functions and tables. For instance, consider the following:

```lua
require('kitty-scrollback').setup {
    global = function()
        return {
            paste_window = { ... },
            kitty_get_text = { ... },
        }
    end,
}
```

can also be configured as 


```lua
require('kitty-scrollback').setup {
    global = {
        paste_window = { ... },
        kitty_get_text = { ... },
    },
}
```

or

```lua
winopts_overrides = function()
    return {
        border = 'rounded',
        row = ...
        col = ...
    }
end
```

could also be configured as:

```lua
winopts_overrides = {
    border = 'rounded',
    row = ...
    col = ...
}
```

There are scenarios where using a function is the most appropriate choice, especially when specific configuration values need to be computed dynamically at runtime. However, there are equally valid situations where the table returned by the function consists of static values that do not require any dynamic computation. In such cases, the function wrapper may appear to introduce unnecessary boilerplate code, potentially complicating the configuration unnecessarily. Thus, offering the option to directly provide a table can greatly simplify the configuration process for these static values, making it more intuitive and concise.

**Comment by mikesmithgh** [comment]
Hey @tummetott, I was reading [kitty.conf](https://sw.kovidgoyal.net/kitty/conf/) and discovered

> Note that environment variables are expanded, so ${USER}.conf becomes name.conf if USER=name. 

I was under the same impression as you that environment variables would not expand in kitty.conf, but it appears that they do. I'm not sure when this was introduced, or if I just overlooked it.

Could you try using `$HOME` ?
```
action_alias kitty-scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
```

I was able to successfully do this on `kitty 0.31.0`. 

If this works, then I don't think a symlink is required anymore. Let me know your thoughts.

**Comment by tummetott** [comment]
yes you are right. it must be an update because i'm pretty sure i tried this a while ago
