### ISSUE TITLE
leader key with LazyVim

### ISSUE THREAD

**Issue by Redoxahmii** [mikesmithgh/kitty-scrollback.nvim#146]
My leader key is set `<space>` and local leader is set `,` but inside kitty-scrollback.nvim it is defaulting to use `\`.
Could be mistake in my setting up so a little help would be beneficial.

```
# Kitty-scrollback.nvim integration

  allow_remote_control yes
 listen_on unix:/tmp/kitty
 shell_integration enabled no-cursor

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map kitty_mod+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
```

This is how i have it setup in kitty.conf and i checked with 

`echo mapleader `
`echo maplocalleader`
These display the correct keys inside neovim.

EDIT:
I used the `echo mapleader` when using the command ctrl+shift+h and ctrl+shift+g command and it comes back as undefined which is if no leader is setup and it is defaulting back to use `\`. As far as i think rn is that it does not pick up the configuration that are applied but uses the default neovim configuration to display the scrollback would be helpful if there is some way to change the leader as using `\` is equivalent to not using this :disappointed:

**Comment by sahinakkaya** [comment]
Maybe you can try passing [`--no-nvim-args`](https://github.com/mikesmithgh/kitty-scrollback.nvim#kitten-arguments) argument to your `kitty_scrollback_nvim` kitten?

```
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --no-nvim-args
```

It should load your neovim config with this option. Since I am lazy loading my config, I don't notice much difference with this option and I benefit from all the power of my neovim when I need.

**Comment by sahinakkaya** [comment]
There is also `--nvim-args` option. Maybe you can set your leader key with just this option and not load your whole config. I didn't try it though. I am not even sure if it is possible to set your leader key from arguments but I think it should be doable.

**Comment by Redoxahmii** [comment]
> Maybe you can try passing [`--no-nvim-args`](https://github.com/mikesmithgh/kitty-scrollback.nvim#kitten-arguments) argument to your `kitty_scrollback_nvim` kitten?
> 
> ```
> action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --no-nvim-args
> ```
> 
> It should load your neovim config with this option. Since I am lazy loading my config, I don't notice much difference with this option and I benefit from all the power of my neovim when I need.

Search a little and found that neovim args provide a `--cmd` flag to run cmd commands 
- Changed the execution line to :
`action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --nvim-args --clean --noplugin -n --cmd "let mapleader=' '"
`
- using `--clean` and `--noplugin` was necessary as loading with `--no-nvim-args` loaded my dashboard.nvim which caused issues so running it like this makes it work.
