### ISSUE TITLE
Neovim loads very long and then opens my dashboard malformed

### ISSUE THREAD

**Issue by PlexSheep** [mikesmithgh/kitty-scrollback.nvim#168]
When I load my neovim with `--no-nvim-args`, it loads for a very long time and the dashboard opens in a malformatted way.

(I was told report this as an issue, see [here](https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/69#issuecomment-1902469493))

![Screenshot_20240121_184113](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/58274330/5a5e5b53-aeb1-46d7-88a0-7686cbf9b892)

![Screenshot_20240121_184135](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/58274330/7ab9750a-2b56-4021-9287-71a661076c4c)

**Configs**:

kitty.conf
```
font_family      FiraCode Nerd Font
font_size 15.0
disable_ligatures never
scrollback_pager nvim -c 'setlocal number|Man!' -c "autocmd VimEnter * normal G" -
enable_audio_bell no
visual_bell_duration 0.01
visual_bell_color yellow
window_alert_on_bell yes
bell_on_tab "🔔 "
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index} {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
foreground #dddddd
background #111111
shell zsh
editor nvim
allow_remote_control socket-only
listen_on unix:///tmp/kitty.sock
env KITTY_TERM=TRUE
shell_integration enabled

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/plex/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --no-nvim-args

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

map alt+e        next_tab
map alt+q     previous_tab
```

[My Neovim config, based on nvchad](https://git.cscherr.de/PlexSheep/neovim-confs)

**Comment by mikesmithgh** [comment]
@PlexSheep oh that does look bad 😂. Thanks for sharing the config, I was able to reproduce the bug

**Comment by mikesmithgh** [comment]
Hey @PlexSheep, I added a fix for this https://github.com/mikesmithgh/kitty-scrollback.nvim/pull/169.

Would you mind testing with branch `nonempty-buffer-fix` and let me know if it is fixed for you?

**Comment by mikesmithgh** [comment]
> I just tested it with the new update, and can confirm that everything works now! This is so cool

Awesome, thanks! Let me know if you hit any other issues 👍
