### ISSUE TITLE
feat: paste window open hook

### ISSUE THREAD

**Issue by ofseed** [mikesmithgh/kitty-scrollback.nvim#197]
Because the paste window needs a common filetype like `bash` to get the correct syntax highlighting and completion, It's hard to do something like setting keymaps or adjusting window options. I suggest exposing a hook function that receives `winid` or `bufnr` as arguments for doing these things.

**Comment by mikesmithgh** [comment]
Hey @ofseed thanks for reporting. 

Regarding adjusting window options, there are overrides exposed via:
| Options                                                           | Type                                                                             | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| :---------------------------------------------------------------- | :------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| paste_window.winopts_overrides                                    | `fun(paste_winopts: KsbWinOpts): table<string,any>?`                             | Paste float window overrides, see nvim_open_win() for configuration                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| paste_window.footer_winopts_overrides                             | `fun(footer_winopts: KsbWinOpts, paste_winopts: KsbWinOpts): table<string,any>?` | Paste footer window overrides, see nvim_open_win() for configuration                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

There is an example of this in [Advanced Configuration Examples](https://github.com/mikesmithgh/kitty-scrollback.nvim/wiki/Advanced-Configuration-Examples) named **ksb_example_paste_win_winopts**. 

But, I agree, there is no general hook if you want to do something based on the `bufnr` or `winid`. What are you trying to trigger when the paste window opens?

**Comment by ofseed** [comment]
I know this option, and I fixed a bug about this : ), see: https://github.com/mikesmithgh/kitty-scrollback.nvim/pull/182

There's a more complicated situation in my use case. I'm using `'statuscolumn'` to arrange my sign columns, there's no way to disable `'statuscolumn'` except a hook to do this.

**Comment by mikesmithgh** [comment]
> I know this option, and I fixed a bug about this : ), see: #182

😅 oops, didn't realize. 


> There's a more complicated situation in my use case. I'm using `'statuscolumn'` to arrange my sign columns, there's no way to disable `'statuscolumn'` except a hook to do this.

Ah, I see yeah you are right.

**Comment by mikesmithgh** [comment]
Hey @ofseed I added the callback `after_paste_window_ready` that has a first parameter containing the window and buffer ids of the scrollback buffer, paste window, and paste window footer. The paste window data will be in form similar to:

```lua
local paste_window_data = {
  scrollback_buffer = { bufid = p.bufid, winid = p.winid },
  paste_window = { bufid = p.paste_bufid, winid = p.paste_winid },
  paste_window_footer = { bufid = p.footer_bufid, winid = p.footer_winid },
}
```

I played around a bit and created this example:

```lua
require('kitty-scrollback').setup({
  {
    callbacks = {
      after_paste_window_ready = function(pastewin_data, kitty_data, opts)
        local stc = '%#ErrorMsg#%{(v:lnum%2)?" ".v:lnum:""}' .. '%#WarningMsg#%{!(v:lnum%2)?" ".v:lnum:""} '
        vim.api.nvim_set_option_value('statuscolumn', stc, {
          win = pastewin_data.paste_window.winid,
        })

        vim.keymap.set({ '' }, '<Tab>', '<Plug>(KsbToggleFooter)', {
          buffer = pastewin_data.paste_window.bufid,
        })

        if pastewin_data.paste_window_footer.winid then
          vim.api.nvim_set_option_value('statuscolumn', 'help:', {
            win = pastewin_data.paste_window_footer.winid,
          })
        end
      end,
    },
  },
})
```

![callback-example](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/10135646/0eee08c2-4e94-435b-a9a4-98f9dee9eacb)

Please let me know if you run into any issues

**Comment by ofseed** [comment]
It runs without problems, thank you!
