### ISSUE TITLE
attempt to call field 'system' (a nil value)

### ISSUE THREAD

**Issue by gio8tisu** [mikesmithgh/kitty-scrollback.nvim#23]
Hello, I'm getting the following error when healthchecking kitty-scrollback from neovim (`KittyScrollbackCheckHealth`):
```
kitty-scrollback: require("kitty-scrollback.health").check()

- ERROR Failed to run healthcheck for "kitty-scrollback" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...pt/kitty-scrollback.nvim/lua/kitty-scrollback/health.lua:246: attempt to call field 'system' (a nil value)
  stack traceback:
  ...pt/kitty-scrollback.nvim/lua/kitty-scrollback/health.lua:246: in function 'check_kitty_scrollback_nvim_version'
  ...pt/kitty-scrollback.nvim/lua/kitty-scrollback/health.lua:280: in function 'check'
  [string "luaeval()"]:1: in main chunk
  [C]: in function 'checkhealth'
  ...r/opt/kitty-scrollback.nvim/lua/kitty-scrollback/api.lua:155: in function ''
  vim/_editor.lua: in function <vim/_editor.lua:0>

```

I tried to follow the installation steps but can't make it through...

Let me know if you need more info.

Thanks in advance!

**Comment by gio8tisu** [comment]
Nevermind, I didn't see that neovim v0.10+ was required. Upgraded and it's working now.

**Comment by mikesmithgh** [comment]
> Nevermind, I didn't see that neovim v0.10+ was required. Upgraded and it's working now.

No worries, I recently modified the checkhealth logic. Previously it would have let you know during that operation. I'll take a look to see what changed so it is easier for new users.
