### ISSUE TITLE
feat: replace ps1 prompt

### ISSUE THREAD

**Issue by szechp** [mikesmithgh/kitty-scrollback.nvim#244]
i don't know if i just could not find this feature in the docs:

is there a way to replace certain things in the buffer that gets opened in neovim?

i have powerlevel10k prompt, like so `❯ `

it would be perfect to strip this before editing the scrollback buffer, for added speed. is there a simple way to do this?

**Comment by mikesmithgh** [comment]
Hi @szechp. Currently, there is no feature to modify the result of the scrollback buffer. kitty-scrollback.nvim uses [kitty @ get-text](https://sw.kovidgoyal.net/kitty/remote-control/#kitten-get-text) to read the contents of the scrollback buffer.

> it would be perfect to strip this before editing the scrollback buffer, for added speed. 

When you say for added speed, what do you mean? Are you referring to loading the scrollback buffer or navigating the buffer after it is already open?

What problem are seeing from `❯ ` ?

**Comment by szechp** [comment]
i should have clarified: with speed i meant editing speed. i can just select whole lines to edit, without having to remove `❯ ` which would make my editing process faster. i think loading would actually take longer, bc of the added processing.

**Comment by mikesmithgh** [comment]
I see, I took a look at https://github.com/romkatv/powerlevel10k. Would you mind sharing a screenshot of your prompt so I can get a better idea?

Do you have a typical sequence of keystroke you do for this? I'm wondering if you could just do `Y` to select from the prompt to end of line. But, it depends on your flow.

**Comment by szechp** [comment]
![Screenshot 2024-05-16 at 08 27 51](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/45265588/78a72fbe-cd8e-4885-b1e2-13e5ea3162ed)

this is my prompt, but i have to admit, i never knew of `Y` before, all i did was go to the char i want, `v`, `$` and then `y`which is quite cumbersome. `Y` is perfekt for what I need 😅 thanks for the help

**Comment by mikesmithgh** [comment]
@szechp awesome! Yep, `Y` is basically `y$` in Neovim. In regular vim `Y` is actually `yy` so it is easy to miss. Glad you are using kitty-scrollback.nvim 😸
