### ISSUE TITLE
bug: autocmd on TermClose breaks kitty-scrollback.nvim

### ISSUE THREAD

**Issue by atimofeev** [mikesmithgh/kitty-scrollback.nvim#265]
### How to reproduce the issue
- Add this code to your nvim config:

```lua
        vim.api.nvim_create_autocmd("TermClose", {
          desc = 'Close terminal if its process has ended',
          callback = function()
             vim.cmd("bdelete")
          end
        })
```

- Launch kitty-scrollback
- kitty-scrollback goes into some 'boot loop' and errors out after 15 sec.
![image](https://github.com/user-attachments/assets/112b197c-3f26-4bbd-8a12-aa8b7aa6ccb2)

### Additional info

I'm not really sure if usage of such autocmd is a good practice, but I would like to report this nonetheless.

**Comment by mikesmithgh** [comment]
Hi @atimofeev thank you for reporting.

kitty-scrollback.nvim uses Neovim's builtin terminal under the hood. So, the autocommand is deleting the scrollback buffer once it completes. If you want to keep that autocommand, you can just disable it for kitty-scrollback.nvim like so:

```lua
if vim.env.KITTY_SCROLLBACK_NVIM ~= 'true' then
  vim.api.nvim_create_autocmd('TermClose', {
    desc = 'Close terminal if its process has ended',
    callback = function()
      vim.cmd('bdelete')
    end,
  })
end
```

**Comment by atimofeev** [comment]
Thank you! The issue was resolved for me.
Feel free to close this, if no further work is planned here.

**Comment by mikesmithgh** [comment]
awesome :+1:
