### ISSUE TITLE
KITTY_SCROLLBACK_NVIM not set during "VimEnter" Autocmd

### ISSUE THREAD

**Issue by georgev93** [mikesmithgh/kitty-scrollback.nvim#286]
I'm using folke's persistence.nvim plugin for session management. I have an autocmd that loads the most recent session during "VimEnter". I'm having my autocmd evaluate KITTY_SCROLLBACK_NVIM before it loads the previous session:

```lua
vim.api.nvim_create_autocmd('VimEnter', {
  desc = 'Auto-load session if there is one for this directory',
  group = vim.api.nvim_create_augroup('autoload-session', { clear = true }),
  once = true,
  callback = function()
    if vim.env.KITTY_SCROLLBACK_NVIM ~= true then
      local current_file = vim.fn.expand('%:p')

      if current_file:find('/%.git/') then
        print('in git dir')
      else
        require('persistence').load()
      end
    end
  end,
  nested = true,
})
```

However, KITTY_SCROLLBACK_NVIM isn't set at this point in the program for some reason. It evaluates correctly later in the code.

Also, for the record, I can't conditionally set the "enabled" parameter of the persistence.nvim plugin, since it's used in an autocmd at VimEnter, it will always be loaded

**Comment by mikesmithgh** [comment]
@georgev93 ah I think I see it, I think you just need to quote 'true'.

```lua
if vim.env.KITTY_SCROLLBACK_NVIM ~= 'true'
```

Since it is an environment variable, it is a string not a boolean.

Please let me know if that works 👍

**Comment by georgev93** [comment]
That was it! Thanks dude! I'm a mega lua n00b.

**Comment by mikesmithgh** [comment]
> That was it! Thanks dude! I'm a mega lua n00b.

Awesome, np. Easy mistake 👍
