### ISSUE TITLE
question: Can you disable the paste window/buffer?

### ISSUE THREAD

**Issue by frnsys** [mikesmithgh/kitty-scrollback.nvim#287]
Hi, thanks for this plugin. Is it possible to disable the paste window? I find myself trying to use `y` to copy a selection and then the paste window comes up, when I'd rather it stick to the regular behavior of copying to my clipboard.

**Comment by mikesmithgh** [comment]
Hey, yep there is a configuration option for that

```lua
    -- boolean? If true, the yank_register copies content to the paste window. If false, disable yank to paste window
    yank_register_enabled = true,
```

see https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file#configuration-options for more options.

For example, if you use lazy.nvim

```lua
return {
  {
    'mikesmithgh/kitty-scrollback.nvim',
    enabled = true,
    cmd = { 'KittyScrollbackGenerateKittens', 'KittyScrollbackCheckHealth' },
    event = { 'User KittyScrollbackLaunch' },
    config = function()
      require('kitty-scrollback').setup({
        {
          paste_window = {
            yank_register_enabled = false,
          },
        },
      })
    end,
  },
}
```

I suppose the name for the option isn't obvious though. It would probably just make more sense to have it `enabled`.

**Comment by frnsys** [comment]
brilliant, thank you!
