### ISSUE TITLE
[Feature Request] Changing colors

### ISSUE THREAD

**Issue by xfzv** [mikesmithgh/kitty-scrollback.nvim#32]
It would be nice if we could change colors.

In current state, the grey color when selecting in visual mode isn't very readable sometimes on my end.

- Regular selection in kitty with `selection_foreground none` and `selection_background none`:
![01](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/78810647/d0839e01-6cba-4c7b-8884-38fdd8d1b01f)

- Selection in visual mode with `kitty-scrollback.nvim`:
![02](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/78810647/ace0fc68-ac6d-4021-906d-3b40e6479bac)

Search results (just for the sake of consistency):

- In Neovim:
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/78810647/fd15b150-d3fa-4a6a-ae04-dedec135f785)

- With `kitty-scrollback.nvim`:
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/78810647/34ace171-1936-4160-969c-4bcaebc03278)

**Comment by mikesmithgh** [comment]
Hey, good catch!

I can add this feature 👍. For a workaround until it is ready you can do:

kitty.conf
```
map ctrl+shift+h kitty_scrollback_nvim --config-file /Users/mike/.config/nvim/lua/kitty-scrollback-nvim-kitten-config.lua # change to filepath of your config
```

kitty-scrollback-nvim-kitty-config.lua
```lua
local M = {}

-- kitten configuration
M.config = function()
  -- vim.g.mapleader = ' '
  -- vim.g.maplocalleader = ','

  return {
    callbacks = {
      after_ready = function(kitty_data)
        local ok, kitty_colors = require('kitty-scrollback.kitty_commands').get_kitty_colors(kitty_data)
        if ok then
          local visual_hl = vim.api.nvim_get_hl(0, { name = 'Visual', link = false })
          vim.api.nvim_set_hl(
            0,
            'Visual',
            vim.tbl_extend('force', visual_hl, {
              -- bg = kitty_colors.selection_background, -- uncomment if you want the same selection background color as Kitty
              fg = kitty_colors.selection_foreground,
            })
          )
        end
      end,
    },
  }
end

return M
```

![kitty-visual-select](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/10135646/b4b872d0-25c3-4310-a119-8a18c9a2b3bf)

I am currently working on redesigning and documenting the configs for kitty-scrollback.nvim so examples like this can be more discoverable. Thanks!

**Comment by mikesmithgh** [comment]
@xfzv Ah, I overlooked `selection_foreground` and `selection_background` to `none` inverts the colors.

This should fix that issue.

kitty-scrollback-nvim-kitty-config.lua

```lua
local M = {}

-- kitten configuration
M.config = function()
  return {
    callbacks = {
      after_ready = function()
        vim.api.nvim_set_hl(0, 'Visual', {
          reverse = true,
        })
      end,
    },
  }
end

return M
```

![invert-hl](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/10135646/43ece355-514f-4d81-a343-76f798f9410f)

**Comment by mikesmithgh** [comment]
Hey @xfzv I just merged the ability to configure Visual highlights.

| Options                                                          | Type                                                                             | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| :--------------------------------------------------------------- | :------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| visual_selection_highlight_mode                                  | `string?`                                                                        | Sets the mode for coloring the Visual highlight group in the scrollback buffer window. `darken` uses a darkened version of the Normal highlight group to improve readability. `kitty` uses the colors defined for `selection_foreground` and `selection_background` in your Kitty configuration. `nvim` uses the default colors defined in the `Visual` highlight group. `reverse` reverses the foreground and background colors of the visual selection.                                                                                                                                                                                                                                                                                                                                            |

## Demo `visual_selection_highlight_mode = 'darken'` (this is the default value)
![kitty-scrollback-nvim-demo](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/10135646/3513aada-c19c-4e4a-bd9e-91b9907a2c8d)

## Demo `visual_selection_highlight_mode = 'reverse'`
![kitty-scrollback-visual-reverse](https://github.com/mikesmithgh/kitty-scrollback.nvim/wiki/assets/kitty_scrollback_screencapture_22_ksb_example_visual_selection_highlight_mode_reverse.gif)

`visual_selection_highlight_mode` allows you to configure the Visual highlight group for the scrollback buffer window with the new highlight group `KittyScrollbackNvimVisual`.

Let me know how this works for you. I am leaving this issue open until I add some better documentation around configuring the plugin using `--no-nvim-args` vs `-u <file>.lua` vs `NVIM_APPNAME`.
