### ISSUE TITLE
Nushell compatibility

### ISSUE THREAD

**Issue by J-Kappes** [mikesmithgh/kitty-scrollback.nvim#56]
Having your default shell set to `nu` causes issues due to the use of `&&` in `kitty_commands.lua`. Could those be replaced with `;` (my workaround) or the `full_cmd` be wrapped in `echo "..." | sh`? Or is there a more elegant solution for letting commands be interpreted by `dash`?

**Comment by mikesmithgh** [comment]
Hey @J-Kappes thanks for the issue and workaround. I'll take a look into this 👍 I have had some issues before with other shell (fish) compatibility around those as well. I think I need to have a more generalized approach

**Comment by mikesmithgh** [comment]
Reproduced:

```sh
brew install nushell
echo '/opt/homebrew/bin/nu' >> /etc/shells
chsh -s /opt/homebrew/bin/nu
```

```

==============================================================================
kitty-scrollback.nvim

ERROR: failed to execute remote Kitty command

*entrypoint:* |termopen()| |::| |exit_code| |~=| |0| 
*command:* kitty @ get-text --match="id:1" --ansi --clear-selection --add-cursor --extent=all | sed -E -e 's/\[\?25.\[.*;.*H\[.*//g' -e 's/$/[0m/g'  && kitty +runpy 'sys.stdout.flush()' && printf ']2;'
*channel_id:* 3
*code:* 1
*stdout:*

  Error: nu::parser::shell_andand
    × The '&&' operator is not supported in Nushell
     ╭─[source:1:1]
   1 │ kitty @ get-text --match="id:1" --ansi --clear-selection --add-cursor --extent=all | sed -E -e 's/[\?25.[.*;.*H[.*//g' -e 's/$//g'  && kitty +runpy 'sys.stdout.flush()' && printf ']2;'
     ·                                                                                                                                           ─┬
     ·                                                                                                                                            ╰── instead of '&&', use ';' or 'and'
     ╰────
    help: use ';' instead of the shell '&&', or 'and' instead of the boolean '&&'

*stderr:*
  <none>

```

**Comment by J-Kappes** [comment]
I found another workaround. Add the following line before `vim.fn.termopen`:
```lua
  vim.cmd("let &shell='/bin/sh'")
```

**Comment by mikesmithgh** [comment]
> I found another workaround. Add the following line before `vim.fn.termopen`:
> 
> ```lua
> 
>   vim.cmd("let &shell='/bin/sh'")
> 
> ```
> 
> I tried executing a Nushell specific command from within the scrollback afterward and it still worked, i.e. setting that variable doesn't affect which shell gets used interactively.

Ohhh that is very clever! I think I may use that. Thanks for the share!

**Comment by mikesmithgh** [comment]
Hey @J-Kappes, I just merged the approach of overriding `shell`. Thanks for the recommendation, let me know if this works or if you have any other issues.

**Comment by J-Kappes** [comment]
The new release works for me, no problem :tada:

**Comment by mikesmithgh** [comment]
> The new release works for me, no problem 🎉

awesome, thanks for looking into it 👍
