### ISSUE TITLE
Output gets cut off towards the bottom

### ISSUE THREAD

**Issue by musjj** [mikesmithgh/kitty-scrollback.nvim#7]
With a huge scrollback, (try running `ls -R` on a big directory), this scrollback displayed by this plugin will get cut off towards the bottom. I noticed the same issue happening with homebrew kitty pager scripts I've found in the wild.

**Comment by mikesmithgh** [comment]
Thanks for the feedback.
- Are you on Linux or Mac?
- Could you provide a screenshot?

**Comment by musjj** [comment]
I'm on Linux.

Before triggering the pager:

![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/72612857/6331309c-4cb3-44ac-8ee2-42aee20c419a)


After triggering the pager:

![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/72612857/b8d9a2fb-c47e-40a4-9985-af8eea3e82f9)

**Comment by mikesmithgh** [comment]
@musjj thanks for the screenshots.

- What shell are you using? (bash, zsh, fish, etc)

- Are there any errors during checkhealth?
```sh
nvim +'KittyScrollbackCheckHealth' +'quit!'
```

- Could you run these two commands and let me know if it produces that same result?
1.
```sh
kitty @ get-text --ansi --extent=all | nvim
```
2.
```sh
kitty @ get-text --ansi --extent=all | sed -e "s/$/\x1b[0m/g" -e "s/\x1b\[\?25.\x1b\[.*;.*H\x1b\[.*//g" | nvim
```

I'm trying to determine if this is coming from Kitty or if it is any of the processing in the plugin.

**Comment by musjj** [comment]
I'm using zsh 5.9
I'm getting one healthcheck error, but I'm not sure if it's relevant:

```
kitty-scrollback: sed ~
- ERROR Failed to run healthcheck for "kitty-scrollback" plugin. Exception:
  ...unwrapped-9ec0ecb/share/nvim/runtime/lua/vim/_system.lua:241: ENOENT: no such file or directory
```

Running `!sed --version` inside nvim works just fine though.

```bash
kitty @ get-text --ansi --extent=all | nvim
```

I'm getting mixed results with this, but I'm not really sure why. Most of the time `nvim` don't end up displaying any contents. I also tried piping to `nvim -u NONE` with similar results. Piping to `vim` (`9.0.1811`) also yields similar results, but interestingly if I wait for a bit I can see the contents of the pipe flowing into the buffer gradually.

It feels like there's some kind of race condition when it comes to piping large text content, either from the `kitty` side or `nvim` side (or both?).

```bash
kitty @ get-text --ansi --extent=all | sed -e "s/$/\x1b[0m/g" -e "s/\x1b\[\?25.\x1b\[.*;.*H\x1b\[.*//g" | nvim
```

I'm seeing similar inconsistencies here, but in this case I usually get a *tiny* bit of content (some kind of terminal escape). But if I repeat the command enough I can sometimes get the complete scrollback of the terminal.

Sorry if there's a lot of vague-ness here, it's a weird issue. Can you reproduce this in your end? That might make debugging it easier.

**Comment by mikesmithgh** [comment]
@musjj Thanks for the info. I'm not able to reproduce the issue. I'll experiment around but any info you have will be helpful 👍

**Comment by musjj** [comment]
Tried to make it more reproducible:

```bash
base64 /dev/urandom | head -c 100000000
kitty @ get-text --ansi --extent=all | nvim -u NONE
```

Try increading the `head` number if the issue doesn't occur. At this point, this might not be a plugin issue but I'm still curious if someone else can reproduce it.

**Comment by mikesmithgh** [comment]
@musjj could you try
```sh
base64 /dev/urandom | head -c 100000000
nvim -u NONE <<< $(kitty @ get-text --ansi --extent=all)
```

This seems to work for me. This waits for the entire stdout before passing to NVIM.

**Comment by musjj** [comment]
This one works for me, it captures the entire scrollback! Can this workaround be used for the plugin?

**Comment by mikesmithgh** [comment]
> This one works for me, it captures the entire scrollback! Can this workaround be used for the plugin?

Great. I'll have to make some changes but should be able to do it 👍

**Comment by mikesmithgh** [comment]
Hey @musjj just an update. This may actually be a bug in Neovim. I'm going to dig in a little deeper and probably open an upstream ticket.

**Comment by mikesmithgh** [comment]
> Tested it out and it works perfectly, thanks a lot for the fix!

🥳 awesome. Thanks for reporting and helping reproduce 👍. I'll have it merged to main probably sometime tomorrow.
