### ISSUE TITLE
Nvim 0.9.4 Attempt to index 'p' a nil value at line 194 api.lua

### ISSUE THREAD

**Issue by restacksyj** [mikesmithgh/kitty-scrollback.nvim#97]
I guess this issue arises when it is unable to connect to Kitty via socket but while running this command in a normal terminal
`kittty --listen-on=unix:/tmp/kitty` it's working

Running Nvim: 0.9.4
![Screenshot 2023-12-10 at 6 54 20 PM](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/25108461/d9438b41-9a11-48c2-b437-20ac8b6545f4)

Here is my kitty.conf

```
allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

action_alias kitty_scrollback_nvim kitten /Users/yashjajoo/.local/share/nvim/site/pack/packer/opt/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

map kitty_mod+h kitty_scrollback_nvim

map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output

mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
```

**Comment by mikesmithgh** [comment]
Hey @restacksyj could you show me your packer config for kitty-scrollback.nvim?

Also, could you try running `:KittyScrollbackCheckHealth` and provide the output?

**Comment by restacksyj** [comment]
![Screenshot 2023-12-10 at 7 15 21 PM](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/25108461/d1ac3f62-41cc-4b04-9ae4-7de9d670cf0a)
Here is the packer config

```
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packe
r/load.lua:91: Vim:Error executing Lua callback: ...r/opt/kitty-scrollback.nvim/lua/kitty-scrollback/api.lua:194: attempt to index upvalue 'p' (a nil value)
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:179: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:175>
        /Users/yashjajoo/.config/nvim/plugin/packer_compiled.lua:415: in function </Users/yashjajoo/.config/nvim/plugin/packer_compiled.lua:414>
```
Here is the output of `:KittyScrollbackCheckHealth`

**Comment by mikesmithgh** [comment]
@restacksyj thanks for the info. Is this only failing for `:KittyScrollbackCheckHealth` ?

what happens if you try to open the scrollback buffer with `ctrl+shift+h` ?

**Comment by restacksyj** [comment]
Hey @mikesmithgh, nothing happens if I press `ctrl+shift+h`

**Comment by mikesmithgh** [comment]
@restacksyj thank you for reporting this, the error you saw during the healthcheck was due to a recent refactor where I forgot to test this scenario. I added a fix and test coverage for that https://github.com/mikesmithgh/kitty-scrollback.nvim/pull/98.

Could you pull the latest and retry?

`:KittyScrollbackCheckHealth` should work now.

Please let me know if kitty-scrollback.nvim is working for you now, or if you see any additional issues.

**Comment by restacksyj** [comment]
Ohh yes!! It's working now
Thanks a lot for the quick response and solution

**Comment by mikesmithgh** [comment]
@restacksyj awesome!

**Comment by one2three4f** [comment]
:checkhealth kitty-scrollback will cause nil value errors (system variable and p variable), just a reminder in case anyone sees this.

**Comment by mikesmithgh** [comment]
> :checkhealth kitty-scrollback will cause nil value errors (system variable and p variable), just a reminder in case anyone sees this.

@one2three4f thanks for the comment, I opened a bug https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/138. That is not expected behavior. It should perform an incomplete checkhealth and recommend the command `:KittyScrollbackCheckHealth` for a full health check. Thanks for noting this!
